### ISSUE TITLE
Getting noise in chrome 53

### ISSUE THREAD

**Issue by adarshk** [mmckegg/freeverb#1] opened 2016-09-20 21:34 UTC
The lib is making crazy noise on chrome 53. It looks like it might be looping in on itself or something to that effect. 

To test copy paste your example in the documentation on http://requirebin.com/ and test it out.

OS: OSX 10.11.4
Browser: Chrome 53.0.2785.116

**Comment by mmckegg** [comment] 2016-09-21 00:03
Thanks for reporting. Yes I've noticed this too. Think it is related to: https://bugs.chromium.org/p/chromium/issues/detail?id=647974

It seems to come right if you adjust its params after a signal starts passing through it. 

It can probably be worked around, but this **is** a bug in Chrome and it's a bad one too.

**Comment by mmckegg** [comment] 2016-09-22 10:02
Actually on investigating, doesn't seem to be ralated to the param bug but instead might be due to https://bugs.chromium.org/p/chromium/issues/detail?id=597432

> The WebAudio spec has changed the definition of the lowpass and
> highpass filters slightly because some lowpass and highpass filters
> could not be represented by the existing filters.  Update
> implementation to match spec.
> 
> This will cause some very slight difference in sound quality for some
> values of Q.  The new filters were careful to preserve the sound as
> much as possible.

**Comment by mmckegg** [comment] 2016-09-22 10:23
[Filed a bug with Tone.js](https://github.com/Tonejs/Tone.js/issues/166) where I originally ripped freeverb from. It has the bug too, maybe someone else can figure it out!!

**Comment by adarshk** [comment] 2016-09-22 12:30
Thanks for taking time to investigate that!

**Comment by mmckegg** [comment] 2016-09-23 01:50
Yes, it is definitely caused by the changes to BiquadFilterNodes. [This issue](https://github.com/WebAudio/web-audio-api/issues/771) documents the changes made. 

There is a handy tool referenced that lets you calculate values that will sound exactly the same in the new filters and the old filters: http://rtoy.github.io/webaudio-hacks/more/biquad/biquad-lowpass-q.html?usedB=true

I tried using it to generate values, and magically the feedback disappeared. We now have a crazy magic Q number of `-3.0102999566398125`, but it WORKS! And it doesn't seem to hurt the sound in older versions of Chrome.

I'm going to go ahead and update this module to use the new value, and hope for the best 😄

**Comment by mmckegg** [comment] 2016-09-23 01:53
Okay, fix released as **v1.0.3**! 🎉

**Closed as completed by mmckegg** 2016-09-23 01:53 UTC
Labels: bug

**Comment by madhukeshayyagari** [comment] 2018-04-10 07:27
Hi, 
I know this library is a old one. But i have checked the implementation of the example using the same example code. The infinite looping still seems to exist. Would you comment on the implementation or what could be changed to make it better. 

Also, I am a newbie, so correct me if iam wrong. In this implementation, the roomSize value only works when the value is >0.6 and <0.8. What changes could be made to have the range from 0 to 0.8.

**Comment by mmckegg** [comment] 2018-04-10 08:35
This was definitely fixed, but maybe something has changed recently in web audio that broke it again. 

I don’t recall room size behaving the way you describe. Maybe that has also been broken. 

What browser?

This code was pulled out of tonejs. There might be a fix on that repo.
